### ISSUE TITLE
this.getSupportActionBar().hide();空指针异常

### ISSUE THREAD

**Issue by ChenJia-X** [Beseting/PhotoBrowse#1]
ImageBrowseActivity#onCreate()第43行

**Comment by Beseting** [comment]
多谢支持！

**Comment by xwjiang2003** [comment]
缩放时报错，pointerIndex out of rang pointerIndex=-1

**Comment by CrystallineDW** [comment]
showUrlImageBrowse报错：
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.appcompat.app.ActionBar.hide()' on a null object reference

**Comment by Beseting** [comment]
ActionBar.hide()报错已修复，新版本见v1.7.3
